Application\Entity\PostEntity:
    properties:
        title:
            - NotBlank:
                message: 'The title field can not be blank!'
                groups: [ newAndEdit ]

Application\Entity\ProfileEntity:
    properties:
        firstName:
            - NotBlank:
                message: 'The first name field can not be blank!'
                groups: [ newAndEdit ]

Application\Entity\RoleEntity:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: role
            message: 'This role is already in use!'
            groups: [ newAndEdit ]
    properties:
        name:
            - NotBlank:
                message: 'The name field can not be blank!'
                groups: [ newAndEdit ]
        role:
            - NotBlank:
                message: 'The role field can not be blank!'
                groups: [ newAndEdit ]

Application\Entity\UserEntity:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            message: 'This email is already in use!'
            groups: [ new, edit, settings ]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: username
            message: 'This username is already in use!'
            groups: [ new, edit, settings ]
    properties:
        username:
            - NotBlank:
                message: 'The username field can not be blank!'
                groups: [ new, edit, settings ]
        email:
            - NotBlank:
                message: 'The email field can not be blank!'
                groups: [ new, edit, settings, resetPasswordRequest ]
            - Email:
                message: 'This email field address is invalid!'
                groups: [ new, edit, settings, resetPasswordRequest ]
        plainPassword:
            - NotBlank:
                message: 'The password field can not be blank!'
                groups: [ new, settingsPassword, resetPasswordReset ]
        profile:
            - Valid: ~
        pinNumber:
            - LessThanOrEqual:
                value: 9999
                message: 'The pin number must be less or equal to 9999!'
                groups: [ new, edit, settings ]
            - GreaterThanOrEqual:
                value: 1000
                message: 'The pin number must be greater or equal to 1000!'
                groups: [ new, edit, settings ]

Application\Entity\WorkingTimeEntity:
    getters:
        timeEndedAfterTimeStarted:
            - 'True':
                message: 'Time ended can not be later then the time started!'
                groups: [ newAndEdit ]
    properties:
        timeStarted:
            - NotBlank:
                message: 'The time started field can not be blank!'
                groups: [ newAndEdit ]
